### ISSUE TITLE
No any time works in Repeat node / until settings if the time will be valid on next day

### ISSUE THREAD

**Issue by Smyl3** [jensrossbach/node-red-contrib-chronos#145]
**Describe the bug**
For repeat node at 'until' option no any time in future works that will be valid only on the next day.

**To reproduce**
1. set a timestamp node and connect it to a chronos-repeat node.
2. Go to 'config Repeat node'
3. set any time at 'until' option that will be valid on the next day
4. click to initiate a timestamp
5. See that nothing happens, no any new time showed at node status with the next trigger time

**Expected behavior**
Expecting to work with any time that will be on next day.

**Context information**
 - Platform & OS: Raspberry OS/dietpi/Linux 6.1.21-v8+ arm64 LE
 - node-red-contrib-chronos version: 1.21.0
 - Node-RED version: 3.1.6
 - Node.js version: 16.20.2

**Comment by jensrossbach** [comment]
Yes, I can confirm the bug.

**Comment by jensrossbach** [comment]
Issue has been fixed with release [1.22](https://github.com/jensrossbach/node-red-contrib-chronos/releases/tag/v1.22.0).

**Comment by Smyl3** [comment]
For some reason in node-red (docker) I still see only version 1.22.0 of node, not 1.22.1 as on npm and node-red website....

**Comment by jensrossbach** [comment]
I don't why that is the case, I don't use Node-RED in a docker container. Maybe you need to wait a bit for it to appear.

Anyway, I strongly recomment to use v1.22.1 instead of 1.22.0 as there was a regression in 1.22.0 introduced (this happened because moment.js introduced a stricter parsing with version 2.30.0 and I tested all the time with an older version, so I didn't notice this).

**Comment by Smyl3** [comment]
It allowed me to update to 1.22.0 only, but does still not show version 1.22.1
Tried restart container etc, nothing worked so far.
Tried to use npm command either without any success.
Weird.
Yeah, I see that 1.22.0 has issue and regardless if I set a trigger time in future, it always triggering instantly.

**Comment by Smyl3** [comment]
All right, it seems I could update the module, but needed a tricky manual method, from inside container.
```
docker exec -it nodered /bin/bash
cd /data/node_modules/
/data/node_modules$ npm list
/data/node_modules$ npm update
```
Thank you the fast update.
